// ============================================
// TCL FASHION — PRODUCT DATA
// Replace `mainColor` / `altColor` with real image or video URLs
// once you have product photos from your supplier. See README.md
// in this project for exact instructions on swapping these in.
// ============================================

const PRODUCTS = [
  {
    id: "p001",
    name: "Aurora Sequin Gown",
    category: "prom",
    tag: "BESTSELLER",
    price: 64.99,
    wasPrice: 89.99,
    mainColor: "linear-gradient(155deg, #FF9EC4, #FF2D6B)",
    altColor: "linear-gradient(155deg, #FF2D6B, #E0114F)",
  },
  {
    id: "p002",
    name: "Stardust Mermaid Dress",
    category: "prom",
    tag: "NEW",
    price: 72.0,
    mainColor: "linear-gradient(155deg, #E8B84B, #C9923A)",
    altColor: "linear-gradient(155deg, #FFE9D6, #E8B84B)",
  },
  {
    id: "p003",
    name: "Velvet Night Slip Dress",
    category: "party",
    tag: null,
    price: 41.5,
    mainColor: "linear-gradient(155deg, #FFC766, #FF7AA0)",
    altColor: "linear-gradient(155deg, #FF7AA0, #FF2D6B)",
  },
  {
    id: "p004",
    name: "Chiffon Wrap Midi",
    category: "wedding",
    tag: null,
    price: 54.0,
    mainColor: "linear-gradient(155deg, #FFE9D6, #E8B84B)",
    altColor: "linear-gradient(155deg, #FFD9E6, #FF8FAE)",
  },
  {
    id: "p005",
    name: "Satin Bow-Back Dress",
    category: "graduation",
    tag: "NEW",
    price: 48.0,
    mainColor: "linear-gradient(155deg, #FFD1DE, #C9436A)",
    altColor: "linear-gradient(155deg, #C9436A, #E0114F)",
  },
  {
    id: "p006",
    name: "Golden Hour Maxi",
    category: "wedding",
    tag: "BESTSELLER",
    price: 67.99,
    wasPrice: 84.99,
    mainColor: "linear-gradient(155deg, #FFF1D6, #E8B84B)",
    altColor: "linear-gradient(155deg, #E8B84B, #C9923A)",
  },
  {
    id: "p007",
    name: "Cascade Ruffle Gown",
    category: "prom",
    tag: null,
    price: 78.5,
    mainColor: "linear-gradient(155deg, #FF8FAE, #E0114F)",
    altColor: "linear-gradient(155deg, #FFD9E6, #FF8FAE)",
  },
  {
    id: "p008",
    name: "Mini Sparkle Dress",
    category: "party",
    tag: "NEW",
    price: 36.99,
    mainColor: "linear-gradient(155deg, #FFC766, #C9436A)",
    altColor: "linear-gradient(155deg, #FF7AA0, #FFC766)",
  },
  {
    id: "p009",
    name: "Pleated Cap-Sleeve Dress",
    category: "graduation",
    tag: null,
    price: 52.0,
    mainColor: "linear-gradient(155deg, #FFD9E6, #FF2D6B)",
    altColor: "linear-gradient(155deg, #FF2D6B, #FF8FAE)",
  },
  {
    id: "p010",
    name: "Twilight Off-Shoulder Gown",
    category: "prom",
    tag: null,
    price: 69.0,
    mainColor: "linear-gradient(155deg, #C9436A, #2B2230)",
    altColor: "linear-gradient(155deg, #E0114F, #C9436A)",
  },
  {
    id: "p011",
    name: "Garden Party Sundress",
    category: "party",
    tag: null,
    price: 39.99,
    mainColor: "linear-gradient(155deg, #FFE9D6, #FFC766)",
    altColor: "linear-gradient(155deg, #FFC766, #E8B84B)",
  },
  {
    id: "p012",
    name: "Lace Trim Wedding Guest Dress",
    category: "wedding",
    tag: "BESTSELLER",
    price: 58.0,
    wasPrice: 72.0,
    mainColor: "linear-gradient(155deg, #FFF9F4, #FFD9E6)",
    altColor: "linear-gradient(155deg, #FFD9E6, #FF9EC4)",
  },
];
